### PR TITLE
Add build started hook

### PR DESCRIPTION
**Pull request by twoqubed**
This will post an event that is similar to what gets posted when a
build is finished. In this case, the status will be "started".

* Implement buildStarted event listener
* Reuse existing buildPayload() method, but pass in the status value.

### CODE REVIEW

**Review by RaviVaranasi — APPROVED** [review]
Is this a case where we need to deploy the plugin to see if it works or could you do local testing ?

**Comment by twoqubed** [comment]
@RaviVaranasi I am working on testing it locally... like I mentioned on Flowdock :wink:

**Comment by Romack** [comment]
@twoqubed, @RaviVaranasi  so we have some stuff that is already listening for build completed events... do they need to be modified first to now check the status?

**Comment by twoqubed** [comment]
@Romack I _think_ the listeners filter on `status` already. We may need to rename some of the listeners so make more sense. @RaviVaranasi and I can take a look at what Goo is doing currently.

**Comment by RaviVaranasi** [comment]
I'm seeing "buildStarted" and "buildFinished" as eventType in splunk.  That is correct, right ?
```
{"name":"Dummy Project :: Dummy Subproject :: Dummy Build","url":"http://172.20.122.206:8111/viewType.html?buildTypeId=DummyProject_DummyBuild","build":{"full_url":"http://172.20.122.206:8111/viewLog.html?buildTypeId=DummyProject_DummyBuild&buildId=14","build_id":"14","eventType":"buildFinished","status":"success","artifacts":{}}}	
```

**Pull request merged**
